spring:
  application:
    name: sqlite-data-jdbc
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:sqlite:db.sqlite

server:
  port: 8080

management:
  server:
    port: 9080
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    java.enabled: true
    env.enabled: true

gg:
  jte:
    usePrecompiledTemplates: true
    localizer:
      inject: true

logging:
  level:
    '[org.apache.catalina.core.ContainerBase]': OFF